/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktek_bioskop;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;


/**
 *
 * @author T I O
 */
public class FormPenjualanTiket extends javax.swing.JFrame {
    
    public FormPenjualanTiket(){
        initComponents();
        table();
    }
    
    public void table(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode");
        tbl.addColumn("Nama");
        tbl.addColumn("Judul_Film");
        tbl.addColumn("Jam_Tayang");
        tbl.addColumn("Jumlah_Tiket");
        tbl.addColumn("No_Kursi");
        tbl.addColumn("Total");
        tabel1.setModel(tbl);
        try {
            Koneksi Koneksi=new Koneksi();
            Statement stat = Koneksi.getConnection().createStatement();
            String sql = "Select * from penjualan_tiket";
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString("Kode"),
                    rs.getString("Nama"),
                    rs.getString("Judul_Film"),
                    rs.getString("Jam_Tayang"),
                    rs.getString("Jumlah_Tiket"),
                    rs.getString("No_Kursi"),
                    rs.getString("Total")
                });
                tabel1.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelharga = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbjamtayang = new javax.swing.JComboBox<>();
        cbjumlahtiket = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        A1 = new javax.swing.JCheckBox();
        A2 = new javax.swing.JCheckBox();
        A3 = new javax.swing.JCheckBox();
        A4 = new javax.swing.JCheckBox();
        B1 = new javax.swing.JCheckBox();
        B2 = new javax.swing.JCheckBox();
        B3 = new javax.swing.JCheckBox();
        B4 = new javax.swing.JCheckBox();
        C1 = new javax.swing.JCheckBox();
        C2 = new javax.swing.JCheckBox();
        C3 = new javax.swing.JCheckBox();
        C4 = new javax.swing.JCheckBox();
        Create = new javax.swing.JButton();
        cbjudulfilm = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tampil_nokursi = new javax.swing.JTextField();
        judulfilm1 = new javax.swing.JTextField();
        jamtayang1 = new javax.swing.JTextField();
        jumlahtiket1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        jLabel9.setText("jLabel9");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("PENJUALAN TIKET BIOSKOP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Judul Film     :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Jam Tayang  : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("No Kursi       :");

        jLabel5.setText("Harga         : ");

        labelharga.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelharga.setText("0");

        jLabel7.setText("RP.");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Jumlah tiket :");

        cbjamtayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "10.00 - 12.00", "13.00 - 15.00", "16.00 - 18.00", "19.00 - 22.00" }));
        cbjamtayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjamtayangActionPerformed(evt);
            }
        });

        cbjumlahtiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbjumlahtiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjumlahtiketActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nama           : ");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        A3.setText("A3");

        A4.setText("A4");

        B1.setText("B1");

        B2.setText("B2");

        B3.setText("B3");

        B4.setText("B4");

        C1.setText("C1");

        C2.setText("C2");

        C3.setText("C3");

        C4.setText("C4");

        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        cbjudulfilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Indiana Jones", "Transformers", "Spiderman Multivers ", "The Conjuring 3 ", "Insidious ", "Guardian Of The Galaxy", "Ip Man 4 " }));
        cbjudulfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjudulfilmActionPerformed(evt);
            }
        });

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Judul_Film", "Jam_Tayang", "Jumlah_Tiket", "No_Kursi", "Total"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel1);

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        keluar.setBackground(new java.awt.Color(204, 204, 204));
        keluar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        keluar.setText("X");
        keluar.setBorder(null);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        tampil_nokursi.setEditable(false);
        tampil_nokursi.setBackground(new java.awt.Color(204, 204, 204));
        tampil_nokursi.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        tampil_nokursi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tampil_nokursi.setText("No Kursi");
        tampil_nokursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampil_nokursiActionPerformed(evt);
            }
        });

        judulfilm1.setEditable(false);
        judulfilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulfilm1ActionPerformed(evt);
            }
        });

        jamtayang1.setEditable(false);
        jamtayang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamtayang1ActionPerformed(evt);
            }
        });

        jumlahtiket1.setEditable(false);
        jumlahtiket1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Kode            :");
        jLabel6.setToolTipText("");

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 220, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(117, 117, 117)
                                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelharga, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(C1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(C2)
                                            .addGap(18, 18, 18)
                                            .addComponent(C3)
                                            .addGap(18, 18, 18)
                                            .addComponent(C4))
                                        .addComponent(tampil_nokursi)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(A1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(A2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(A3))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(B1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(B2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B3)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jumlahtiket1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(B4)
                                                .addComponent(A4)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbjudulfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbjumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbjamtayang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(75, 75, 75)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(judulfilm1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                        .addComponent(jamtayang1))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Create)
                                .addGap(18, 18, 18)
                                .addComponent(Update)
                                .addGap(18, 18, 18)
                                .addComponent(Delete)
                                .addGap(18, 18, 18)
                                .addComponent(Refresh)
                                .addGap(270, 270, 270)))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKode)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbjudulfilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judulfilm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbjamtayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamtayang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbjumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahtiket1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A1)
                        .addComponent(A2)
                        .addComponent(A3)
                        .addComponent(A4)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(B3)
                    .addComponent(B4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C1)
                    .addComponent(C2)
                    .addComponent(C3)
                    .addComponent(C4))
                .addGap(8, 8, 8)
                .addComponent(tampil_nokursi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7))
                    .addComponent(labelharga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Create, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(906, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbjumlahtiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjumlahtiketActionPerformed
        String selectedValue= cbjumlahtiket.getSelectedItem().toString();
       
        int hargabarang= 40000;
        
        jumlahtiket1.setText(selectedValue);
        if(cbjumlahtiket.getSelectedItem()=="1"){
            labelharga.setText("40000");
        }else if(cbjumlahtiket.getSelectedItem()=="2"){
            labelharga.setText("80000");
        }else if(cbjumlahtiket.getSelectedItem()=="3"){
            labelharga.setText("120000");
        }else if(cbjumlahtiket.getSelectedItem()=="4"){
            labelharga.setText("160000");
        }else if(cbjumlahtiket.getSelectedItem()=="5"){
            labelharga.setText("200000");
        }else if(cbjumlahtiket.getSelectedItem()=="6"){
            labelharga.setText("240000");
        }else if(cbjumlahtiket.getSelectedItem()=="7"){
            labelharga.setText("280000");
        }else if(cbjumlahtiket.getSelectedItem()=="8"){
            labelharga.setText("320000");
        }else if(cbjumlahtiket.getSelectedItem()=="9"){
            labelharga.setText("360000");
        }else if(cbjumlahtiket.getSelectedItem()=="10"){
            labelharga.setText("400000");
        }
       
        
    }//GEN-LAST:event_cbjumlahtiketActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
                // TODO add your handling code here:
        String sql;
        ResultSet res;
        String kode = txtKode.getText();
        String nama = txtnama.getText();
        
        int judulfilm = cbjudulfilm.getSelectedIndex();
        String judulfilm2 = judulfilm1.getSelectedText();
        
        int jamtayang = cbjamtayang.getSelectedIndex();
        String jamtayang2 = jamtayang1.getText();
        
        int jumlahtiket = cbjumlahtiket.getSelectedIndex();
        String jumlahtiket2 = jumlahtiket1.getText();
        
        String nokursi = tampil_nokursi.getText();
        
        int total = labelharga.getComponentCount();
        
        String selectedValue= cbjudulfilm.getSelectedItem().toString();
        
        judulfilm1.setText(selectedValue);
        
        nokursi = "";
        if(A1.isSelected()){
            nokursi += A1.getText() + ", ";
        }
        if(A2.isSelected()){
            nokursi += A2.getText() + ", ";
        }
        if(A3.isSelected()){
            nokursi += A3.getText() + ", ";
        }
        if(A4.isSelected()){
            nokursi += A4.getText() + ", ";
        }
        if(B1.isSelected()){
            nokursi += B1.getText() + ", ";
        }
        if(B2.isSelected()){
            nokursi += B2.getText() + ", ";
        }
        if(B3.isSelected()){
            nokursi += B3.getText() + ", ";
        }
        if(B4.isSelected()){
            nokursi += B4.getText() + ", ";
        }
        if(C1.isSelected()){
            nokursi += C1.getText() + ", ";
        }
        if(C2.isSelected()){
            nokursi += C2.getText() + ", ";
        }
        if(C3.isSelected()){
            nokursi += C3.getText() + ", ";
        }if(C4.isSelected()){
            nokursi += C4.getText() + ", ";
        }else{
            nokursi = nokursi.substring(0, nokursi.length()-2) + ", ";
            tampil_nokursi.setText(nokursi);
        }
        
        int hargasatuan = 0;
        
        
        if (judulfilm == 0){
            JOptionPane.showMessageDialog(null, "Judul film belum diisi !!");
        }else if(judulfilm == 1){
            judulfilm2 = ("Indiana Jones");
            hargasatuan = 40000;
        }else if(judulfilm == 2){
            judulfilm2 = "Transformers";
            hargasatuan = 40000;
        }else if(judulfilm == 3){
            judulfilm2 = "Spiderman Multivers";
            hargasatuan = 40000;
        }else if(judulfilm == 4){
            judulfilm2 = "The Conjuring 3";
            hargasatuan = 40000;
        }else if(judulfilm == 5){
            judulfilm2 = "Insidious";
            hargasatuan = 40000;
        }else if(judulfilm == 6){
            judulfilm2 = "Guardian Of The Galaxy";
            hargasatuan = 40000;
        }else if(judulfilm == 7){
            judulfilm2 = "Ip Man 4";
            hargasatuan = 40000;
        }
        total = hargasatuan * jumlahtiket;
        
        
        jumlahtiket1.setText(selectedValue);
        if(cbjumlahtiket.getSelectedItem()=="1"){
            labelharga.setText("40000");
        }else if(cbjumlahtiket.getSelectedItem()=="2"){
            labelharga.setText("80000");
        }else if(cbjumlahtiket.getSelectedItem()=="3"){
            labelharga.setText("120000");
        }else if(cbjumlahtiket.getSelectedItem()=="4"){
            labelharga.setText("160000");
        }else if(cbjumlahtiket.getSelectedItem()=="5"){
            labelharga.setText("200000");
        }else if(cbjumlahtiket.getSelectedItem()=="6"){
            labelharga.setText("240000");
        }else if(cbjumlahtiket.getSelectedItem()=="7"){
            labelharga.setText("280000");
        }else if(cbjumlahtiket.getSelectedItem()=="8"){
            labelharga.setText("320000");
        }else if(cbjumlahtiket.getSelectedItem()=="9"){
            labelharga.setText("360000");
        }else if(cbjumlahtiket.getSelectedItem()=="10"){
            labelharga.setText("400000");
        }
        
       
        
        
        try{
            Koneksi Koneksi = new Koneksi();
            Connection conn = Koneksi.getConnection();
            Statement stat = conn.createStatement();
            
            
            sql = "select * from penjualan_tiket where Kode ='"+kode+"'";
            res = stat.executeQuery(sql);
            
            if(res.next()){
                JOptionPane.showMessageDialog(this, "Nama sudah ada!");
                return;
            }
            
            sql = String.format("insert into penjualan_tiket values('%s','%s','%s','%s','%s','%s','%s')",kode, nama, judulfilm2,jamtayang2, jumlahtiket2, nokursi, total);
            int res_update = stat.executeUpdate(sql);
            
            if(res_update == 1){
                JOptionPane.showMessageDialog(this, "Sukses ditambahkan!");
                table();
                conn.close();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Penambahan Gagal");
        }
        table();
    }//GEN-LAST:event_CreateActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
           txtnama.setText("");
           txtKode.setText("");
           cbjudulfilm.setSelectedIndex(0);
           cbjamtayang.setSelectedIndex(0);
           cbjumlahtiket.setSelectedIndex(0);
           tampil_nokursi.setText("");
           judulfilm1.setText("");
           jamtayang1.setText("");
           jumlahtiket1.setText("");
           labelharga.setText("0");
           A1.setSelected(false);
           A2.setSelected(false);
           A3.setSelected(false);
           A4.setSelected(false);
           B1.setSelected(false);
           B2.setSelected(false);
           B3.setSelected(false);
           B4.setSelected(false);
           C1.setSelected(false);
           C2.setSelected(false);
           C3.setSelected(false);
           C4.setSelected(false);
           
           
    }//GEN-LAST:event_RefreshActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Keluar aplikasi", "Konfirmasi", JOptionPane.OK_OPTION);
        
        if (pilih == JOptionPane.OK_OPTION){
            System.exit(0);
        }else{
            JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
       
    }//GEN-LAST:event_A1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
    
    }//GEN-LAST:event_A2ActionPerformed

    private void tampil_nokursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampil_nokursiActionPerformed

    }//GEN-LAST:event_tampil_nokursiActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
                // TODO add your handling code here:
        String sql;
        ResultSet res;
        String kode = txtKode.getText();
        String nama = txtnama.getText();
        
        int judulfilm = cbjudulfilm.getSelectedIndex();
        String judulfilm2 = judulfilm1.getSelectedText();
        
        int jamtayang = cbjamtayang.getSelectedIndex();
        String jamtayang2 = jamtayang1.getText();
        
        int jumlahtiket = cbjumlahtiket.getSelectedIndex();
        String jumlahtiket2 = jumlahtiket1.getText();
        
        String nokursi = tampil_nokursi.getText();
        
        String selectedValue= cbjudulfilm.getSelectedItem().toString();
        
        judulfilm1.setText(selectedValue);
        
        int total = labelharga.getComponentCount();
        
        nokursi = "";
        if(A1.isSelected()){
            nokursi += A1.getText() + ", ";
        }
        if(A2.isSelected()){
            nokursi += A2.getText() + ", ";
        }
        if(A3.isSelected()){
            nokursi += A3.getText() + ", ";
        }
        if(A4.isSelected()){
            nokursi += A4.getText() + ", ";
        }
        if(B1.isSelected()){
            nokursi += B1.getText() + ", ";
        }
        if(B2.isSelected()){
            nokursi += B2.getText() + ", ";
        }
        if(B3.isSelected()){
            nokursi += B3.getText() + ", ";
        }
        if(B4.isSelected()){
            nokursi += B4.getText() + ", ";
        }
        if(C1.isSelected()){
            nokursi += C1.getText() + ", ";
        }
        if(C2.isSelected()){
            nokursi += C2.getText() + ", ";
        }
        if(C3.isSelected()){
            nokursi += C3.getText() + ", ";
        }if(C4.isSelected()){
            nokursi += C4.getText() + ", ";
        }else{
            nokursi = nokursi.substring(0, nokursi.length()-2) + ", ";
            tampil_nokursi.setText(nokursi);
        }
        
        jumlahtiket1.setText(selectedValue);
        if(cbjumlahtiket.getSelectedItem()=="1"){
            labelharga.setText("40000");
        }else if(cbjumlahtiket.getSelectedItem()=="2"){
            labelharga.setText("80000");
        }else if(cbjumlahtiket.getSelectedItem()=="3"){
            labelharga.setText("120000");
        }else if(cbjumlahtiket.getSelectedItem()=="4"){
            labelharga.setText("160000");
        }else if(cbjumlahtiket.getSelectedItem()=="5"){
            labelharga.setText("200000");
        }else if(cbjumlahtiket.getSelectedItem()=="6"){
            labelharga.setText("240000");
        }else if(cbjumlahtiket.getSelectedItem()=="7"){
            labelharga.setText("280000");
        }else if(cbjumlahtiket.getSelectedItem()=="8"){
            labelharga.setText("320000");
        }else if(cbjumlahtiket.getSelectedItem()=="9"){
            labelharga.setText("360000");
        }else if(cbjumlahtiket.getSelectedItem()=="10"){
            labelharga.setText("400000");
        }
        
         int hargasatuan = 0;
         
        if (judulfilm == 0){
            JOptionPane.showMessageDialog(null, "Judul film belum diisi !!");
        }else if(judulfilm == 1){
            judulfilm2 = ("Indiana Jones");
            hargasatuan = 40000;
        }else if(judulfilm == 2){
            judulfilm2 = "Transformers";
            hargasatuan = 40000;
        }else if(judulfilm == 3){
            judulfilm2 = "Spiderman Multivers";
            hargasatuan = 40000;
        }else if(judulfilm == 4){
            judulfilm2 = "The Conjuring 3";
            hargasatuan = 40000;
        }else if(judulfilm == 5){
            judulfilm2 = "Insidious";
            hargasatuan = 40000;
        }else if(judulfilm == 6){
            judulfilm2 = "Guardian Of The Galaxy";
            hargasatuan = 40000;
        }else if(judulfilm == 7){
            judulfilm2 = "Ip Man 4";
            hargasatuan = 40000;
        }
        total = hargasatuan * jumlahtiket;
            try
                {
                        Koneksi cntiket = new Koneksi();
                        Connection con = cntiket.getConnection();
                        Statement stat = con.createStatement();
                        String strsql = ("update penjualan_tiket set Nama = '" +nama+ "',Judul_Film='"+judulfilm2+"',Jam_Tayang='"+jamtayang2+"',Jumlah_Tiket='"+jumlahtiket2+"',No_Kursi='"+nokursi+"',Total='"+total+"' where Kode='"+kode+"';");
                    
                    int stsproses = stat.executeUpdate(strsql);
                        if(stsproses==1)
                        JOptionPane.showMessageDialog(this, "Sukses Diedit!");
                        con.close();
                        
                } 
            catch(SQLException e)
            {
                    JOptionPane.showMessageDialog(this, "Koreksi Gagal!"+e.getMessage());
        System.err.println("Kesalahan perintah SQL : " +e.getMessage());            
            }  
    table();               
    }//GEN-LAST:event_UpdateActionPerformed

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        int row = tabel1.getSelectedRow();
        txtKode.setText((String)tabel1.getValueAt(row, 0));
        txtnama.setText((String)tabel1.getValueAt(row, 1));
        judulfilm1.setText((String)tabel1.getValueAt(row, 2));
        jamtayang1.setText((String)tabel1.getValueAt(row, 3));
        jumlahtiket1.setText((String)tabel1.getValueAt(row, 4));
        tampil_nokursi.setText((String)tabel1.getValueAt(row, 5));
        labelharga.setText((String)tabel1.getValueAt(row, 6));        // TODO add your handling code here:
    }//GEN-LAST:event_tabel1MouseClicked

    private void judulfilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulfilm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulfilm1ActionPerformed

    private void jamtayang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamtayang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamtayang1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int stt = JOptionPane.showConfirmDialog(this, "Yakin dihapus?");
        System.out.print(stt);
        String kode = txtKode.getText();
        if (stt == 0)
        {
        
        String nama = txtnama.getText();
        try
                {
                 Koneksi cntiket = new Koneksi();
                 Connection con = cntiket.getConnection();
                 Statement stat = con.createStatement();
                String strsql = ("delete from penjualan_tiket where Kode='" +kode+ "';");
                int stsproses = stat.executeUpdate(strsql);
                if (stsproses == 1)
                JOptionPane.showMessageDialog(this,"Data Terhapus!");
                con.close();
                }
        catch (Exception e){
        JOptionPane.showMessageDialog(this, "data gagal dihapus");
        System.err.println("Kesalahan perintah SQL : " +  e.getMessage());
        }
        table();
        }    
       
    }//GEN-LAST:event_DeleteActionPerformed

    private void cbjudulfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjudulfilmActionPerformed
        String selectedValue= cbjudulfilm.getSelectedItem().toString();
        
        judulfilm1.setText(selectedValue);

        
    }//GEN-LAST:event_cbjudulfilmActionPerformed

    private void cbjamtayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjamtayangActionPerformed
        String selectedValue= cbjamtayang.getSelectedItem().toString();
        
        jamtayang1.setText(selectedValue);
            
        
    }//GEN-LAST:event_cbjamtayangActionPerformed

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualanTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A1;
    private javax.swing.JCheckBox A2;
    private javax.swing.JCheckBox A3;
    private javax.swing.JCheckBox A4;
    private javax.swing.JCheckBox B1;
    private javax.swing.JCheckBox B2;
    private javax.swing.JCheckBox B3;
    private javax.swing.JCheckBox B4;
    private javax.swing.JCheckBox C1;
    private javax.swing.JCheckBox C2;
    private javax.swing.JCheckBox C3;
    private javax.swing.JCheckBox C4;
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbjamtayang;
    private javax.swing.JComboBox<String> cbjudulfilm;
    private javax.swing.JComboBox<String> cbjumlahtiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jamtayang1;
    private javax.swing.JTextField judulfilm1;
    private javax.swing.JTextField jumlahtiket1;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel labelharga;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField tampil_nokursi;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
